# -*- coding: utf-8 -*-
"""Active Learning Interface

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaHqU8ez4lsMtNwUJrbIoGlQy5qBjes-
"""

# THE HEADLINE SHIFT — Active Learning Annotation App (Gradio)
    # Applied ML Final Project · Berrocal, Delong, Dong, Koepp



# IMPORTING PACKAGES
import gradio as gr
import pandas as pd
import csv
import random
from collections import defaultdict
from datetime import datetime
from pathlib import Path



#  CONFIGURATION

from google.colab import files
uploaded = files.upload()
CSV_PATH = "allsides.csv"

CSV_COLUMN_MAP = {
    "heading":     "headline",
    "source":      "outlet",
    "tags":        "topic",
    "bias_rating": "ideology",
}

ANNOTATIONS_CSV   = "annotations.csv"
PAIRS_PER_SESSION = 20
SHARE             = False   # True = temporary 72hr link. Use HF Spaces instead (see above).

# Annotation dimensions — shown as radio buttons (1–5); UI builds itself from this list
DIMENSIONS = [
    {
        "id":    "emotion",
        "label": "Emotional Intensity",
        "desc":  "How emotionally charged is the more sensationalist headline?",
    },
    {
        "id":    "value_laden",
        "label": "Value-Laden Language",
        "desc":  "Does it express a clear evaluative or political stance?",
    },
]

# Radio button choices shown to annotators (value → display label)
SCALE = {
    "1": "1 — Neutral / Factual",
    "2": "2",
    "3": "3 — Moderate",
    "4": "4",
    "5": "5 — Extreme / Strongly opinionated",
}



#  DATA LOADING

def load_headlines():
    path = Path(CSV_PATH)
    if not path.exists():
        raise FileNotFoundError(
            f"CSV not found at:\n  {CSV_PATH}\n"
            "Check the path. On HF Spaces use just the filename."
        )

    df = pd.read_csv(path)
    print(f"Raw shape: {df.shape} | Columns: {list(df.columns)}")

    rename = {orig: internal for orig, internal in CSV_COLUMN_MAP.items()
              if orig in df.columns}
    df = df.rename(columns=rename)

    for orig in CSV_COLUMN_MAP:
        if orig not in rename:
            print(f"  Warning: '{orig}' not in CSV — skipping.")

    if "outlet"   not in df.columns: df["outlet"]   = "Unknown"
    if "topic"    not in df.columns: df["topic"]     = "unknown"
    if "ideology" not in df.columns: df["ideology"]  = "unknown"

    # Tags are comma-separated — keep first tag only for display
    def first_tag(val):
        if pd.isna(val) or str(val).strip() == "":
            return "unknown"
        return str(val).split(",")[0].strip()

    df["topic"] = df["topic"].apply(first_tag)

    df = df.dropna(subset=["headline"])
    df = df[df["headline"].str.strip() != ""].reset_index(drop=True)

    print(f"Loaded {len(df)} headlines.")
    print(df["ideology"].value_counts().to_string())
    return df


HEADLINES_DF = load_headlines()



#  PAIR GENERATION

def make_pairs(df, n, seed=None):
    """Randomly samples n unique pairs. Swaps A/B randomly to reduce position bias."""
    rng = random.Random(seed)
    indices = list(df.index)
    used, pairs = set(), []
    attempts = 0

    while len(pairs) < n and attempts < n * 30:
        attempts += 1
        i, j = rng.sample(indices, 2)
        key = (min(i, j), max(i, j))
        if key in used:
            continue
        used.add(key)
        if rng.random() > 0.5:
            i, j = j, i
        ra, rb = df.loc[i], df.loc[j]
        pairs.append({
            "pair_key":   f"{min(i,j)}-{max(i,j)}",
            "idx_a":      int(i),
            "headline_a": str(ra["headline"]),
            "outlet_a":   str(ra["outlet"]),
            "topic_a":    str(ra["topic"]),
            "ideology_a": str(ra["ideology"]),
            "idx_b":      int(j),
            "headline_b": str(rb["headline"]),
            "outlet_b":   str(rb["outlet"]),
            "topic_b":    str(rb["topic"]),
            "ideology_b": str(rb["ideology"]),
        })
    return pairs



#  CSV STORAGE

CSV_FIELDNAMES = [
    "annotator_id", "pair_num", "pair_key",
    "idx_a", "headline_a", "outlet_a", "topic_a", "ideology_a",
    "idx_b", "headline_b", "outlet_b", "topic_b", "ideology_b",
    "winner",
    *[f"rating_{d['id']}" for d in DIMENSIONS],
    "timestamp",
]

def ensure_csv():
    if not Path(ANNOTATIONS_CSV).exists():
        with open(ANNOTATIONS_CSV, "w", newline="", encoding="utf-8") as f:
            csv.DictWriter(f, fieldnames=CSV_FIELDNAMES).writeheader()

def append_row(record: dict):
    ensure_csv()
    with open(ANNOTATIONS_CSV, "a", newline="", encoding="utf-8") as f:
        csv.DictWriter(f, fieldnames=CSV_FIELDNAMES, extrasaction="ignore").writerow(record)



#  APP LOGIC

def _render(state):
    """Returns updated values for all UI components on each new pair."""
    pairs = state["pairs"]
    idx   = state["pair_idx"]
    done  = len(state["annotations"])
    total = len(pairs)

    if idx >= total:
        return (
            f"All done! {done}/{total} pairs annotated.",
            done / total,
            "", "", "", "",
            gr.update(visible=False),  # dim_block
            gr.update(visible=True),   # done_block
            gr.update(visible=True),   # annotation_block
        )

    pair = pairs[idx]
    return (
        f"Pair {done + 1} of {total}  ·  {state['annotator_id']}",
        done / total,
        f"**{pair['headline_a']}**",
        "",
        f"**{pair['headline_b']}**",
        "",
        gr.update(visible=False),
        gr.update(visible=False),
        gr.update(visible=True),
    )


def fn_start(name, state):
    name = name.strip()
    if not name:
        return state, *([gr.update()] * 9), "Please enter your name first."

    seed = hash(name) % 100_000
    state.update({
        "annotator_id": name,
        "pairs":        make_pairs(HEADLINES_DF, PAIRS_PER_SESSION, seed=seed),
        "pair_idx":     0,
        "annotations":  [],
        "winner":       None,
        "ratings":      {},
    })
    return state, *_render(state), gr.update(visible=False), ""


def fn_select(choice, state):
    state["winner"] = choice
    pair = state["pairs"][state["pair_idx"]]
    labels = {
        "A":   pair["headline_a"][:80] + "…",
        "B":   pair["headline_b"][:80] + "…",
        "tie": "(equal / can't decide)",
    }
    show_dims = choice != "tie"
    msg = f"Selected: **{labels[choice]}**"
    msg += "" if show_dims else " — click Submit to continue."
    return state, gr.update(visible=show_dims), msg


def fn_submit(state, *radio_vals):
    """radio_vals is one string per DIMENSION, e.g. ("3", "4") — or None if not picked."""
    if not state.get("winner"):
        return state, *([gr.update()] * 9), "Pick A, B, or Equal first."

    # Check all dimensions are rated (unless it's a tie)
    if state["winner"] != "tie":
        if any(v is None for v in radio_vals):
            return state, *([gr.update()] * 9), "Please rate all dimensions before submitting."

    for dim, val in zip(DIMENSIONS, radio_vals):
        state["ratings"][dim["id"]] = int(val) if val else None

    pair   = state["pairs"][state["pair_idx"]]
    record = {
        "annotator_id": state["annotator_id"],
        "pair_num":     len(state["annotations"]) + 1,
        "pair_key":     pair["pair_key"],
        "idx_a":        pair["idx_a"],
        "headline_a":   pair["headline_a"],
        "outlet_a":     pair["outlet_a"],
        "topic_a":      pair["topic_a"],
        "ideology_a":   pair["ideology_a"],
        "idx_b":        pair["idx_b"],
        "headline_b":   pair["headline_b"],
        "outlet_b":     pair["outlet_b"],
        "topic_b":      pair["topic_b"],
        "ideology_b":   pair["ideology_b"],
        "winner":       state["winner"],
        **{f"rating_{d['id']}": state["ratings"].get(d["id"]) for d in DIMENSIONS},
        "timestamp":    datetime.now().isoformat(),
    }

    append_row(record)
    state["annotations"].append(record)
    state["pair_idx"] += 1
    state["winner"]    = None
    state["ratings"]   = {}

    return state, *_render(state), f"Saved pair {record['pair_num']}."


def fn_skip(state):
    state["pair_idx"] += 1
    state["winner"]    = None
    state["ratings"]   = {}
    return state, *_render(state), "Skipped."



#  GRADIO UI

with gr.Blocks(title="Headline Rater", theme=gr.themes.Soft()) as demo:

    state = gr.State({
        "annotator_id": "",
        "pairs":        [],
        "pair_idx":     0,
        "annotations":  [],
        "winner":       None,
        "ratings":      {},
    })

    gr.Markdown("""
    # 📰 Headline Rater
    **The Headline Shift · Active Learning Annotation Tool**

    Compare 20 pairs of real U.S. news headlines and tell us which feels more sensationalist.
    Takes about **5 minutes**.
    """)

    # ── Welcome ──────────────────────────────────────────────────────────────
    with gr.Group() as welcome_block:
        name_box  = gr.Textbox(label="Your UNI",
                               placeholder="e.g. abc1234", max_lines=1)
        start_btn = gr.Button("Start →", variant="primary")
        start_msg = gr.Markdown("")

    # ── Annotation ───────────────────────────────────────────────────────────
    with gr.Group(visible=False) as annotation_block:

        progress_label = gr.Markdown("Pair 1 of 20")
        progress_bar   = gr.Slider(0, 1, value=0, interactive=False,
                                   show_label=False)

        gr.Markdown("### Which headline uses more **emotional, alarming, or value-laden** language?")

        with gr.Row():
            with gr.Column():
                gr.Markdown("#### Headline A")
                hl_a     = gr.Markdown("—")
                outlet_a = gr.Markdown("—")
                btn_a    = gr.Button("👆 A is more sensationalist", variant="secondary")

            with gr.Column(scale=0, min_width=50):
                gr.Markdown("<br><br><br>**VS**")

            with gr.Column():
                gr.Markdown("#### Headline B")
                hl_b     = gr.Markdown("—")
                outlet_b = gr.Markdown("—")
                btn_b    = gr.Button("👆 B is more sensationalist", variant="secondary")

        btn_tie    = gr.Button("≈ About equal / can't decide", variant="secondary")
        winner_msg = gr.Markdown("")

        # ── Dimension ratings — radio buttons, hidden until winner chosen ───
        with gr.Group(visible=False) as dim_block:
            gr.Markdown("---\n**Now rate the winning headline:**")
            radio_inputs = []
            for dim in DIMENSIONS:
                r = gr.Radio(
                    choices=list(SCALE.values()),
                    label=f"{dim['label']} — {dim['desc']}",
                    value=None,       # no default → forces a conscious choice
                    interactive=True,
                )
                radio_inputs.append(r)

        with gr.Row():
            submit_btn = gr.Button("Submit & Next →", variant="primary")
            skip_btn   = gr.Button("Skip →",          variant="secondary")

        status_msg = gr.Markdown("")

        with gr.Group(visible=False) as done_block:
            gr.Markdown(f"""
            ---
            ## ✅ You're done — thank you!
            Responses saved to **`{ANNOTATIONS_CSV}`**.
            If you're on Hugging Face Spaces, the team can download
            annotations.csv from the Files tab.
            """)

    # ── Output list — must match _render return order exactly ────────────────
    render_outs = [
        progress_label, progress_bar,
        hl_a, outlet_a, hl_b, outlet_b,
        dim_block, done_block, annotation_block,
    ]

    # ── Wire up radio choices → internal string values ("1"–"5") ─────────────
    # Gradio returns the display label; we map back to the numeric string.
    SCALE_REVERSE = {v: k for k, v in SCALE.items()}

    def _strip_radio(val):
        """Convert display label back to numeric string, or None."""
        if val is None:
            return None
        return SCALE_REVERSE.get(val, val.split("—")[0].strip())

    def fn_submit_wrapped(state, *raw_radio_vals):
        mapped = tuple(_strip_radio(v) for v in raw_radio_vals)
        return fn_submit(state, *mapped)

    # ── Events ───────────────────────────────────────────────────────────────
    start_btn.click(
        fn=fn_start,
        inputs=[name_box, state],
        outputs=[state, *render_outs, welcome_block, start_msg],
    )

    for btn, choice in [(btn_a, "A"), (btn_b, "B"), (btn_tie, "tie")]:
        btn.click(
            fn=lambda s, c=choice: fn_select(c, s),
            inputs=[state],
            outputs=[state, dim_block, winner_msg],
        )

    submit_btn.click(
        fn=fn_submit_wrapped,
        inputs=[state, *radio_inputs],
        outputs=[state, *render_outs, status_msg],
    )
    skip_btn.click(
        fn=fn_skip,
        inputs=[state],
        outputs=[state, *render_outs, status_msg],
    )



#  LAUNCH

if __name__ == "__main__":
    ensure_csv()
    demo.launch(share=SHARE)